### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by KyryloKilin** [polymerdao/developer-hub#50]
1. A broken link on the page: https://docs.polymerlabs.org/docs/learn/concepts/vibc/channel-creation/ 
![image](https://github.com/polymerdao/developer-hub/assets/83702309/6c49bb7c-e5ec-48eb-81d5-7ff1b50773b8)

2. A broken link on the page: https://docs.polymerlabs.org/docs/build/ibc-solidity/vibc-core/ 
![image](https://github.com/polymerdao/developer-hub/assets/83702309/c668d6b4-640e-4215-a3cb-d0f6083d4266)

3. A broken links on the page: https://docs.polymerlabs.org/docs/build/ibc-solidity/ 
![image](https://github.com/polymerdao/developer-hub/assets/83702309/e389c7ad-ed5d-4bf9-9d6f-3c81a3009bc1)
![image](https://github.com/polymerdao/developer-hub/assets/83702309/aecfc344-ca5d-4ed2-9653-4c8880cf4abb)
![image](https://github.com/polymerdao/developer-hub/assets/83702309/4fcac303-a659-4301-9aed-0372c3171813)

4. A broken links on the page: https://docs.polymerlabs.org/docs/build/ibc-solidity/universal-channel/ 
![image](https://github.com/polymerdao/developer-hub/assets/83702309/471fd121-9f79-4bd8-9c6a-e5525c354190)
![image](https://github.com/polymerdao/developer-hub/assets/83702309/723c7dd2-fc1b-4b23-b10d-ea05a259ee0e)

```[tasklist]
### Tasks
```

**Comment by tmsdkeys** [comment]
Thanks for flagging. Working on updating

**Comment by tmsdkeys** [comment]
Should be resolved with #59
