### ISSUE TITLE
The edit this article button at the bottom of the document does not work

### ISSUE THREAD

**Issue by zm-moon** [polymerdao/developer-hub#51]
The edit this article button at the bottom of the [document ](https://github.com/polymerdao/developer-hub/docs/learn/concepts/ibc/ibc-clients.md)does not work.
![image](https://github.com/polymerdao/developer-hub/assets/42063103/746173ba-7abd-4e07-850b-708c794d4562)

The content of the redirected page is 'Not Found'

**Comment by tmsdkeys** [comment]
Should be resolved with #59
